run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - pkg/sms/mocks
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/org/project
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  lll:
    line-length: 120
    tab-width: 1
  nakedret:
    max-func-lines: 30
linters:
  enable-all: false
  enable:
    - errcheck
    - golint
    - gofmt
    - goimports
    - gocyclo
    - maligned
    - dupl
    - goconst
    - lll
    - nakedret
  fast: false
