version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/golang:1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/martinsirbe/go-sms
    steps:
      - checkout
      - run:
          name: Download project dependencies.
          command: go mod download
      - run:
          name: Run golangci-lint.
          command: |
            go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
            golangci-lint run -v
      - run:
          name: Run tests.
          command: make tests
      - codecov/upload:
          file: coverage.txt
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build a docker image.
          command: |
            docker build \
              -t martinsirbe/go-sms:$(git rev-parse --short $CIRCLE_SHA1) \
              -t martinsirbe/go-sms:latest \
              -f Dockerfile .
      - run:
          name: Push the docker image to docker hub.
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push martinsirbe/go-sms:$(git rev-parse --short $CIRCLE_SHA1)
            docker push martinsirbe/go-sms:latest
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
  periodic-build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
